<?php

/**
 * Created by DigitalUp.
 * Author: Dionisis Papanik
 * Date: 23/6/2016
 */
 
 
$helper = Mage::helper("digitalup_fbpixel");
if (!$helper->isVisitorPixelEnabled()) {
    return;
}
$id = $helper->getVisitorPixelId();
if ( $helper->isDynamicRemarketingEnabled() == 0 ){
    $pixeltype  = $this->FBpageType();
}elseif ( $helper->isDynamicRemarketingEnabled() == 1 ){
    $pixeltype  = $this->FBpageRemarketingType();
}else {
    $pixeltype  = 'error!';
}
?>
<!-- Facebook Pixel Code -->
<script>
    !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','//connect.facebook.net/en_US/fbevents.js');

    fbq('init', '<?php echo $id ?>');
    fbq('track', 'PageView');
    <?php echo $pixeltype; ?>
</script>
<noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=<?php echo $id ?>&ev=PageView&noscript=1"/></noscript>
<!-- End Facebook Pixel Code -->
